# Generated by Django 2.2.1 on 2019-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_point_spread_league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
